### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Noreaster76**

### CODE REVIEW

**Comment by STRML** [comment]
Are you seeing any output with this version? On `master`, OSX 10.11, I have no actual saved file:

```bash
~/g/f/i/B/P/Release ((d1b9722...)|✚1) $ imagesnap -w 2
Capturing image from device "<AVCaptureDALDevice: 0xabcd [FaceTime HD Camera][xxxxx]>"...
~/g/f/i/B/P/Release ((d1b9722...)|✚1) $ ll
total 64
-rwxr-xr-x  1 samuelreed  staff    31K Nov 24 13:02 imagesnap
~/g/f/i/B/P/Release ((d1b9722...)|✚1) $
```

**Comment by Noreaster76** [comment]
Yes, I get picture files:

```
➜  /tmp imagesnap -t 1 -d "FaceTime HD Camera"
```
After letting it run for a few seconds...
```
^C
➜  /tmp ls -ltr *.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx   17455 Nov 24 21:38 snapshot-00000-2016-11-24_21-38-10.432.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx  229023 Nov 24 21:38 snapshot-00001-2016-11-24_21-38-11.435.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx  215256 Nov 24 21:38 snapshot-00002-2016-11-24_21-38-12.436.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx  231968 Nov 24 21:38 snapshot-00003-2016-11-24_21-38-13.437.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx  211681 Nov 24 21:38 snapshot-00004-2016-11-24_21-38-14.439.jpg
-rw-r--r--  1 xxxxxxxx  xxxxxxxx  199906 Nov 24 21:38 snapshot-00005-2016-11-24_21-38-15.440.jpg
➜  /tmp
```

I'm not getting any output with the parameters you used, however:

```
➜  /tmp imagesnap -w 2
Capturing image from device "<AVCaptureDALDevice: 0xabcd [FaceTime HD Camera][xxxxx]>"...%                                                                    ➜  /tmp ls -ltr *.jpg
ls: *.jpg: No such file or directory
➜  /tmp
```

Does it work if you use the parameters I listed in my example above? And are you sure you're on the right commit? The most recent commit on my fork is c513b6be3f94c8d3ddc23376bb4dc468b19589d9.

**Comment by Noreaster76** [comment]
@STRML Oh, and I'm on OS X El Capitan as well, yes.

**Comment by STRML** [comment]
I have the same behavior you see, on `c513b6b` as well (I was trying out one of the branches). The interval command works fine, but the single image cmd produces no output.

**Comment by Noreaster76** [comment]
@STRML Sounds like this calls for creating an issue.

**Comment by STRML** [comment]
:+1:

**Pull request merged**
